# ============================================================================
# Kustomize Base â€” platform-api
# ============================================================================
# Contains all resources shared across environments.
# Overlays patch these for environment-specific config.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-api

labels:
  - pairs:
      app.kubernetes.io/part-of: platform-engineering
    includeSelectors: false

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - hpa.yaml
  - pdb.yaml
  - resourcequota.yaml
  - limitrange.yaml
